/************************************************************************/
/* FAN 0.99A4                                                           */
/* Last Scan Date function prototypes/definitions                       */
/************************************************************************/
#ifndef __FAN_SDT.H
#define __FAN_SDT.H

#define SCANDATE_ID     0x99A33A99L
void LoadScanDate (char *filename);
void SaveScanDate (char *filename);

#endif
