/************************************************************************/
/* FAN 0.99A4                                                           */
/* External data declarations                                           */
/************************************************************************/
#ifndef __FAN_DATA_H
#define __FAN_DATA_H

extern time_t  LastScanDate;
extern Config *config;
extern char    ConfigFilename [120];
extern int     ResetDateFlag;                   // Just resetting to 0?

#endif
